{
 "title": "temp & clouds",
 "time": { "from": "2025-09-15T07:00:00.000Z", "to": "2025-09-20T06:59:59.000Z" },
 "panels": [
  { "title": "Seattle", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT temp_f FROM current_weather WHERE location='Seattle, US';"
    }
   ]
  },
  {
   "title": "Temperature & Clouds",
   "type": "timeseries",
   "description": "Show Data for upcoming 5 days",
   "gridPos": { "h": 7, "w": 19, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "rawSql": "SELECT\n  forecast_time,\n  temp_f\nFROM\n  weather_forecast_3h\n WHERE location='Seattle, US';"
    },
    {
     "rawSql": "SELECT forecast_time, wind_mph FROM weather_forecast_3h  WHERE location='Portland, US';"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT wind_mph FROM current_weather  WHERE location='Seattle, US';"
    }
   ]
  },
  {
   "title": "Chance of Rain",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT chance_of_rain_percent from current_weather  WHERE location='Seattle, US';"
    }
   ]
  },
  {
   "title": "Pleasantness",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 19, "x": 4, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT forecast_time, pleasantness_score FROM weather_forecast_3h WHERE location='Seattle, US';"
    }
   ]
  },
  {
   "title": "Humidity, Cloudiness & Rain",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT forecast_time, humidity_percent, cloudiness_percent, rain_percent FROM weather_forecast_3h WHERE location='Seattle, US';"
    }
   ]
  },
  {
   "title": "Cloudiness",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cloudiness_percent from current_weather WHERE location='Seattle, US';"
    }
   ]
  },
  { "title": "Portland, OR", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Current Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT temp_f FROM current_weather  WHERE location='Portland, US';"
    }
   ]
  },
  {
   "title": "Temperature & Clouds",
   "type": "timeseries",
   "description": "Show Data for upcoming 5 days",
   "gridPos": { "h": 7, "w": 19, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "rawSql": "SELECT\n  forecast_time,\n  temp_f\nFROM\n  weather_forecast_3h\n WHERE location='Portland, US';"
    },
    {
     "rawSql": "SELECT forecast_time, wind_mph FROM weather_forecast_3h  WHERE location='Portland, US';"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT wind_mph FROM current_weather  WHERE location='Portland, US';"
    }
   ]
  },
  {
   "title": "Chance of Rain",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT chance_of_rain_percent from current_weather  WHERE location='Portland, US';"
    }
   ]
  },
  {
   "title": "Pleasantness",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 19, "x": 4, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT forecast_time, pleasantness_score FROM weather_forecast_3h WHERE location='Portland, US';"
    }
   ]
  },
  {
   "title": "Humidity, Cloudiness & Rain",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 4, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT forecast_time, humidity_percent, cloudiness_percent, rain_percent FROM weather_forecast_3h WHERE location='Portland, US';"
    }
   ]
  },
  {
   "title": "Cloudiness",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cloudiness_percent from current_weather WHERE location='Portland, US';"
    }
   ]
  }
 ]
}